### PR TITLE
update acorn version to better handle the object pattern

### PR DESCRIPTION
**Pull request by AlexisTessier**
Due to an error in the old version of acorn, it is impossible to use the key name "set" in a object pattern, like that :

`function load2({set = 'hello'}) {
	return load('tt');
}`

I just updated the acorn dependency.

I also added a test to check this specific use case but I'm not sure it's pertinent because the real issue is that the dependency was not up to date.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
this looks good. could you remove the package-lock file and use the `^` semver operator in the dependency, so we'll get future updates too?

**Comment by AlexisTessier** [comment]
Done in the last commit.

**Comment by goto-bus-stop** [comment]
perf, thanks!

**Comment by goto-bus-stop** [comment]
📦 4.6.0

**Pull request merged**
