### PR TITLE
Add rest spread support

### PR DESCRIPTION
**Pull request by bcomnes**
Detective was throwing when used with newer node code that uses spread operators.  This adds a plugin to acorn which enables support for the spread operator until there is better built in support in acorn.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
we can prob drop node 0.12 together with the major bump for #73

**Comment by bcomnes** [comment]
I’m in favor or dropping 0.12, given that nobody should be using it at this point.  I would want to bounce that off the most active maintainer before doing so though. 

I’m not totally up to speed which features we should of be supporting at this point but maybe it would be worth doing a thorough rundown at some point.

**Comment by bcomnes** [comment]
@substack interested in your opinion on what we should do wrt semver and dropping support for 0.12.

**Comment by bcomnes** [comment]
> <substack> bret: I guess it makes sense to bump the major to drop 0.12
18:19 plenty of numbers, might as well
18:20 <bret> Bret Comnes substack: I can take care of the related 0.12 tasks related to this PR (namely, the workaround to ignore the test when run in 0.12) but I'm not to familiar with the code base.  We can leave other cleanup tasks to other PRs I'm thinking
18:21 I think this will bring rest spread 'support' to browserify and fam 
18:27 substack: ok I'll go ahead and do that
18:29 substack: this will cascade into a module-deps and browserify major release as well?
18:30 <substack> probably?
18:34 <bret> Bret Comnes Ok, I'll see how far I can get

**Comment by bcomnes** [comment]
Rolled back 0.12 support on the PR.

**Comment by ljharb** [comment]
We absolutely should not have dropped older node support. This needs to be restored.

**Comment by bcomnes** [comment]
Can you elaborate?  Happy to restore.

**Comment by ljharb** [comment]
So far my tests in older nodes are failing in browserify 15 due solely to arrow syntax being used (in detective, i think?). That's a really silly reason to break things. Either we should stick with ES5 syntax or we should use a build process prepublish, as is npm best practice.

**Comment by bcomnes** [comment]
Looks like my commits that supported 0.12 were pruned in the branch.  I'll push those back up for reference.

**Comment by bcomnes** [comment]
@ljharb I saved it actually for this very situation.  Yay me from a few days ago: https://github.com/bcomnes/detective/tree/0.12

**Pull request merged**
